### ISSUE TITLE
mixed_bag::terse_output test fails

### ISSUE THREAD

**Issue by Dinnerbone** [LukasKalbertodt/libtest-mimic#26]
It relies on the duration always being 0s and apparently my PC is being pessimistic and rounds it up.

![image](https://user-images.githubusercontent.com/317625/215100848-e25fd1bd-19cf-4191-89ae-43f37cf88d9f.png)

```
thread 'terse_output' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
 running 16 tests
 .F.Fiiii.F.Fiiii
 failures:
 
 ---- dog ----
 was not a good boy
 
 ---- bunny ----
 jumped too high
 
 ---- blue ----
 sky fell down
 
 ---- green ----
 was poisoned
 
 
 failures:
     dog
     bunny
     blue
     green
 
<test result: FAILED. 4 passed; 4 failed; 8 ignored; 0 measured; 0 filtered out; finished in 0.01s
>test result: FAILED. 4 passed; 4 failed; 8 ignored; 0 measured; 0 filtered out; finished in 0.00s

', tests\mixed_bag.rs:502:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\core\src\panicking.rs:65
   2: mixed_bag::terse_output
             at .\tests\mixed_bag.rs:502
   3: mixed_bag::terse_output::closure$0
             at .\tests\mixed_bag.rs:493
   4: core::ops::function::FnOnce::call_once<mixed_bag::terse_output::closure_env$0,tuple$<> >
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6\library\core\src\ops\function.rs:251
   5: core::ops::function::FnOnce::call_once
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\core\src\ops\function.rs:251
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


```

**Comment by LukasKalbertodt** [comment]
Ouchy. Yeah, I figured this would bite me eventually :D
